<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>steps.rb</string>
	</array>
  <key>foldingStartMarker</key>
  <string>^\s*\b(Dado|Quando|Então|E|Ou|Funcionalidade|Esquema do Cenário|Cenário|Exemplos|Mas|)</string>
  <key>foldingStopMarker</key>
  <string>^\s*(end)$</string>
	<key>keyEquivalent</key>
	<string>^~C</string>
	<key>name</key>
	<string>Gherkin/Cucumber pt-br</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(Exemplos|Dado|Quando|Então|E|Ou|Funcionalidade|Esquema do Cenário|Cenário|Mas|)\b</string>
			<key>name</key>
			<string>keyword.other.step.cucumber</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(?&lt;=Exemplos|Dado|Quando|Então|E|Ou|Funcionalidade|Esquema do Cenário|Cenário|Mas|) (")</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.ruby</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.ruby</string>
				</dict>
			</dict>
		<key>comment</key>
			<string>string</string>
			<key>contentName</key>
			<string>string.quoted.step.cucumber.classic.ruby</string>
			<key>end</key>
			<string>((\1))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#interpolated_ruby</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#regex_sub</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(?&lt;=Exemplos|Dado|Quando|Então|E|Ou|Funcionalidade|Esquema do Cenário|Cenário|Mas|) (/)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.classic.ruby</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.ruby</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>regular expression after a Cucumber keyword</string>
			<key>contentName</key>
			<string>string.regexp.step.cucumber.classic.ruby</string>
			<key>end</key>
			<string>((/[eimnosux]*))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#regex_sub</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>source.ruby</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ruby.rspec.cucumber.steps</string>
	<key>uuid</key>
	<string>B269B8F3-3A6D-4169-9E70-DD89A679416A</string>
</dict>
</plist>
